### ISSUE TITLE
ошибки вместо данных в поле Time in statuses

### ISSUE THREAD

**Issue by Arbitr108** [AndreyVMarkelov/andreymarkelov-atlas-plugins-datacollector#1]
https://yadi.sk/i/buMqNiw1gZw6Z

**Comment by AndreyVMarkelov** [comment]
Which version of jira and plugin?

**Comment by Arbitr108** [comment]
plugin version Version: 1.2.5
jira version  v6.0.7

**Comment by AndreyVMarkelov** [comment]
https://marketplace.atlassian.com/plugins/ru.andreymarkelov.atlas.plugins.datacollector/versions

Plugin version 1.2.5 is suitable onlt for JIRA 6.4.x
